@extends('fe.master')
@section('header')
    @include('fe.header')
@endsection
@section('logo')
    @include('fe.logo')
@endsection
@section('fe.part.product')
    @include('fe.part.product')
@endsection
